0add user messages to prevent running wrong scripts

diff --git a/cosypose/run-in-container b/cosypose/run-in-container
--- a/cosypose/run-in-container
+++ b/cosypose/run-in-container
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ -z "${APPTAINER_ENVIRONMENT}" ]; then
+    echo "This script cannot be run directly and must be started by the application container"
+    exit 1
+fi
+
 . /pyenv/conda/etc/profile.d/conda.sh
 conda activate /pyenv/app
 
diff --git a/cupy/run-in-container b/cupy/run-in-container
--- a/cupy/run-in-container
+++ b/cupy/run-in-container
@@ -1,5 +1,10 @@
 #!/bin/bash -x
 
+if [ -z "${APPTAINER_ENVIRONMENT}" ]; then
+    echo "This script cannot be run directly and must be started by the application container"
+    exit 1
+fi
+
 unset CUDA_VISIBLE_DEVICES    # necessary !?
 
 nvidia-smi
diff --git a/testgl/run-in-container b/testgl/run-in-container
--- a/testgl/run-in-container
+++ b/testgl/run-in-container
@@ -1,4 +1,9 @@
-#!/bin/bash -x
+#!/bin/bash
+
+if [ -z "${APPTAINER_ENVIRONMENT}" ]; then
+    echo "This script cannot be run directly and must be started by the application container"
+    exit 1
+fi
 
 echo "DRI in container:"
 ls -alr /dev/dri
